server.port: 8080
jwt.secretKey: asdfuasjf9a8s7fd89ihq34kljruyf98ayshcskdhfioafsuyfdcjha890sduf

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: users-service
          uri: ${USER_SERVICE_URI:lb://users-service}
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=2

        - id: posts-service
          uri: ${POSTS_SERVICE_URI:lb://posts-service}
          predicates:
            - Path=/api/v1/posts/**
          filters:
            - StripPrefix=2
            - -name: AuthenticationFilter

        - id: connections-service
          uri: ${CONNECTIONS_SERVICE_URI:lb://connections-service}
          predicates:
            - Path=/api/v1/connections/**
          filters:
            - StripPrefix=2
            - -name: AuthenticationFilter
